Server:
  Port:     :8081
  Model:    debug
#mysql
Mysql:
  Username:     root    #用户名
  Password:     root    #密码
  Host:         127.0.0.1:3306
  DBName:       ssf        #数据库名称
  TablePrefix:  ssf_        #数据库表名前缀
  Charset:      utf8    #链接字符格式
  ParseTime:    True
  MaxIdleConns: 10
  MaxOpenConns: 30
  ConnMaxIdleTime:    120 #连接池空闲的最长时间 按照数据库中的值进行设置
  ConnMaxLifetime:    120 #可重用连接的最长时间


Redis:
  Host:         127.0.0.1:6379 #地址
  Password:                   #密码
  DB:           2             #数据库

Jwt:
  AppKey:  xfdada
  AppSecret: papapa
  Expire:    7200
  Issuer:    xf

Logger:
  AppPath: D:/GOAPP/src/gin-icqqg/runtime/app       #请求日志存储位置
  AppLevel: info
  SqlPath: D:/GOAPP/src/gin-icqqg/runtime/sql       #SQL日志存储位置
  SqlLevel: info
