// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate_swagger = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Xfdada",
            "email": "xiangfudada@163.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/captcha": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "固定接口"
                ],
                "summary": "生成验证码",
                "responses": {
                    "200": {
                        "description": "{\"id\":\"string\",\"url\":\"sdfasfasd\"}成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/news": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "新闻相关接口"
                ],
                "summary": "新增新闻",
                "parameters": [
                    {
                        "type": "string",
                        "description": "新闻标题",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "新闻描述",
                        "name": "desc",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "新闻图",
                        "name": "thumb",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "新闻关键词",
                        "name": "seo_keyword",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "新闻tag",
                        "name": "tags",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "新闻内容",
                        "name": "content",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "新闻类别",
                        "name": "cate_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "新闻点赞数",
                        "name": "zan",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "新闻热门",
                        "name": "hot",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "新闻查看数",
                        "name": "see_num",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "新闻是否置顶",
                        "name": "type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "新闻是否显示",
                        "name": "show",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 200, \"msg\": \"success\"}",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "400": {
                        "description": "{\"code\": 101, \"msg\": \"参数错误\"} 请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "{\"code\": 102, \"msg\": \"未找到结果\"} 内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            }
        },
        "/api/v1/news/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "新闻相关接口"
                ],
                "summary": "通过ID获取新闻详细信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "新闻ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/model.News"
                        }
                    },
                    "400": {
                        "description": "code\": 101, \"msg\": \"参数错误\"} \"请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "code\": 102, \"msg\": \"未找到结果\"} \"内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "新闻相关接口"
                ],
                "summary": "删除新闻",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "新闻ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 200, \"msg\": \"success\"}",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "400": {
                        "description": "{\"code\": 101, \"msg\": \"参数错误\"} 请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "{\"code\": 102, \"msg\": \"未找到结果\"} 内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            }
        },
        "/api/v1/sendSms": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "固定接口"
                ],
                "summary": "发送短信",
                "parameters": [
                    {
                        "type": "string",
                        "description": " 手机号",
                        "name": "phone",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/upload": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图片上传接口"
                ],
                "summary": "图片上传",
                "parameters": [
                    {
                        "type": "file",
                        "description": "file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 200, \"msg\": \"success\"}",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "400": {
                        "description": "{\"code\": 101, \"msg\": \"参数错误\"} 请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "{\"code\": 102, \"msg\": \"未找到结果\"} 内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            }
        },
        "/api/v1/user": {
            "put": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户接口"
                ],
                "summary": "用户更新信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": " 用户名",
                        "name": "user_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " 性别",
                        "name": "sex",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " 手机号",
                        "name": "phone",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " 邮箱",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":\"更新成功\"}成功",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户接口"
                ],
                "summary": "新增用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": " 用户名",
                        "name": "user_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " 手机号",
                        "name": "phone",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " 密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " 邮箱",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " 头像",
                        "name": "avatar",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": " 性别",
                        "name": "sex",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    },
                    "400": {
                        "description": "请求错误"
                    },
                    "500": {
                        "description": "内部错误"
                    }
                }
            }
        },
        "/api/v1/user/login": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户接口"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": " 手机号",
                        "name": "phone",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " 密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " 验证码ID",
                        "name": "captcha_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " 验证码",
                        "name": "captcha_value",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            }
        },
        "/api/v1/user/update_avatar": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户接口"
                ],
                "summary": "用户更换头像",
                "parameters": [
                    {
                        "type": "file",
                        "description": "file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"url\":\"\"}成功",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            }
        },
        "/api/v1/user/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户接口"
                ],
                "summary": "获取用户详细信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    "400": {
                        "description": "请求错误"
                    },
                    "500": {
                        "description": "内部错误"
                    }
                }
            }
        },
        "/api/web/menu": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后端菜单模块"
                ],
                "summary": "添加菜单信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "排序升序",
                        "name": "sort",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "菜单标题",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "菜单路由",
                        "name": "url",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "是否显示 1是 2否",
                        "name": "show",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "父级ID",
                        "name": "parent_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"success\"}",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            }
        },
        "/api/web/menu/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后端菜单模块"
                ],
                "summary": "获取菜单信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":model.Menu}",
                        "schema": {
                            "$ref": "#/definitions/model.Menu"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            },
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后端菜单模块"
                ],
                "summary": "修改菜单信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "排序升序",
                        "name": "sort",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "菜单标题",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "菜单路由",
                        "name": "url",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "是否显示 1是 2否",
                        "name": "show",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "父级ID",
                        "name": "parent_id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"success\"}",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后端菜单模块"
                ],
                "summary": "删除菜单信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"success\"}",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            }
        },
        "/api/web/menuList": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后端菜单模块"
                ],
                "summary": "菜单列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":[]model.Menu}",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Menu"
                            }
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            }
        },
        "/api/web/menuTree": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后端菜单模块"
                ],
                "summary": "获取菜单层级信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":[]map[string]interface{}}",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            }
        },
        "/api/web/permission": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后端权限模块"
                ],
                "summary": "添加权限信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "权限名",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "权限中文名",
                        "name": "tag",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求路径",
                        "name": "http_path",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "空为any 任何方法，get,put,post",
                        "name": "http_method",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "父级ID",
                        "name": "parent_id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"success\"}",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            }
        },
        "/api/web/permission/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后端权限模块"
                ],
                "summary": "获取权限信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":model.Permission}",
                        "schema": {
                            "$ref": "#/definitions/model.Permissions"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            },
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后端权限模块"
                ],
                "summary": "修改权限信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "权限名",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "权限中文名",
                        "name": "tag",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "请求路径",
                        "name": "http_path",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "空为any 任何方法，get,put,post",
                        "name": "http_method",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "父级ID",
                        "name": "parent_id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"success\"}",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后端权限模块"
                ],
                "summary": "删除权限信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"success\"}",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            }
        },
        "/api/web/permissionList": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后端权限模块"
                ],
                "summary": "顶级权限列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":[]model.Permission}",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Permissions"
                            }
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            }
        },
        "/api/web/permissionTree": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后端权限模块"
                ],
                "summary": "获取权限层级信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":[]map[string]interface{}}",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            }
        },
        "/api/web/product": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台产品模块"
                ],
                "summary": "添加产品信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "名称",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "标题",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "型号",
                        "name": "version",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"success\"}",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            }
        },
        "/api/web/product/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台产品模块"
                ],
                "summary": "获取产品信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":model.Product}",
                        "schema": {
                            "$ref": "#/definitions/model.Product"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台产品模块"
                ],
                "summary": "删除产品信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"success\"}",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            }
        },
        "/api/web/product/{id}/edit": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台产品模块"
                ],
                "summary": "修改产品信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "名称",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "标题",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "型号",
                        "name": "version",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"success\"}",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            }
        },
        "/api/web/productList": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台产品模块"
                ],
                "summary": "产品列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":[]model.Product}",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Product"
                            }
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            }
        },
        "/api/web/role": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后端角色模块"
                ],
                "summary": "添加角色信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "角色英文名",
                        "name": "role_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "角色中文名",
                        "name": "role_tag",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "菜单ID字符串1，2，3",
                        "name": "menu_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "权限ID字符串 1，2，3",
                        "name": "permissions_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"success\"}",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            }
        },
        "/api/web/role/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后端角色模块"
                ],
                "summary": "获取角色信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":model.Role}",
                        "schema": {
                            "$ref": "#/definitions/model.Role"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            },
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后端菜单模块"
                ],
                "summary": "修改菜单信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "角色英文名",
                        "name": "role_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "角色中文名",
                        "name": "role_tag",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "菜单ID字符串1，2，3",
                        "name": "menu_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "权限ID字符串 1，2，3",
                        "name": "permissions_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"success\"}",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后端角色模块"
                ],
                "summary": "删除角色信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"success\"}",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            }
        },
        "/api/web/roleList": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后端角色模块"
                ],
                "summary": "角色列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":[]model.Menu}",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Role"
                            }
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            }
        },
        "/api/web/user": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后端管理员模块"
                ],
                "summary": "获取自身信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":model.AdminUser}",
                        "schema": {
                            "$ref": "#/definitions/model.AdminUser"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后端管理员模块"
                ],
                "summary": "新增管理员",
                "parameters": [
                    {
                        "type": "string",
                        "description": " 用户名",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " 密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " 姓名",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"新增成功\"}",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            }
        },
        "/api/web/user/login": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后端用户接口"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": " 用户名",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " 密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " 验证码ID",
                        "name": "captcha_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " 验证码",
                        "name": "captcha_value",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            }
        },
        "/api/web/user/logout": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后端用户接口"
                ],
                "summary": "用户注销",
                "parameters": [
                    {
                        "type": "string",
                        "description": " token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"注销成功\"}",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            }
        },
        "/api/web/user/{username}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后端管理员模块"
                ],
                "summary": "删除管理员",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "账号名",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":[]model.AdminUser}",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.AdminUser"
                            }
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            }
        },
        "/api/web/userIsOpen": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后端管理员模块"
                ],
                "summary": "管理员是否启用",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "账号名",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "是否启用",
                        "name": "is_open",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":[]model.AdminUser}",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.AdminUser"
                            }
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            }
        },
        "/api/web/userList": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后端管理员模块"
                ],
                "summary": "获取管理员列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":[]model.AdminUser}",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.AdminUser"
                            }
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.AdminUser": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "头像",
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "id": {
                    "description": "ID",
                    "type": "integer"
                },
                "is_open": {
                    "description": "是否启用 1是 2否",
                    "type": "integer"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "remember_token": {
                    "description": "免登录token",
                    "type": "string"
                },
                "user_name": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "model.Menu": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "parent_id": {
                    "description": "父级ID",
                    "type": "integer"
                },
                "show": {
                    "description": "是否展示 1是 2否",
                    "type": "integer"
                },
                "sort": {
                    "description": "菜单排序",
                    "type": "integer"
                },
                "title": {
                    "description": "菜单名称",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "url": {
                    "description": "路由地址",
                    "type": "string"
                }
            }
        },
        "model.News": {
            "type": "object",
            "properties": {
                "cate_id": {
                    "description": "归属类别",
                    "type": "integer"
                },
                "content": {
                    "description": "新闻内容",
                    "type": "string"
                },
                "desc": {
                    "description": "新闻简介",
                    "type": "string"
                },
                "hot": {
                    "description": "是否热门 1是 2否",
                    "type": "integer"
                },
                "id": {
                    "description": "id",
                    "type": "integer"
                },
                "see_num": {
                    "description": "查看数量",
                    "type": "integer"
                },
                "seo_keyword": {
                    "description": "新闻关键词",
                    "type": "string"
                },
                "show": {
                    "description": "是否显示 1是 2 否",
                    "type": "integer"
                },
                "tags": {
                    "description": "新闻tag",
                    "type": "string"
                },
                "thumb": {
                    "description": "新闻图片",
                    "type": "string"
                },
                "title": {
                    "description": "新闻标题",
                    "type": "string"
                },
                "type": {
                    "description": "产品类型",
                    "type": "integer"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "integer"
                },
                "zan": {
                    "description": "点赞数量",
                    "type": "integer"
                }
            }
        },
        "model.Permissions": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "http_method": {
                    "description": "请求方法  空为任何方法 ，GET，POST，PUT，DELETE，PATCH，OPTIONS",
                    "type": "string"
                },
                "http_path": {
                    "description": "请求路径",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "description": "权限英文名",
                    "type": "string"
                },
                "parent_id": {
                    "description": "父级ID",
                    "type": "integer"
                },
                "tag": {
                    "description": "权限名称",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.Product": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "model.Role": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "menu_id": {
                    "description": "菜单ID    用逗号分隔例如 1，2，3，4",
                    "type": "string"
                },
                "permissions_id": {
                    "description": "权限ID    用逗号分隔例如 1，2，3，4",
                    "type": "string"
                },
                "role_name": {
                    "description": "角色名称",
                    "type": "string"
                },
                "role_tag": {
                    "description": "角色标签",
                    "type": "string"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "model.User": {
            "type": "object",
            "required": [
                "avatar",
                "email",
                "phone",
                "user_name"
            ],
            "properties": {
                "avatar": {
                    "description": "头像",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "email_bind": {
                    "description": "邮箱绑定 1是 2否",
                    "type": "integer"
                },
                "email_sing": {
                    "description": "邮箱注册 1是 2否",
                    "type": "integer"
                },
                "id": {
                    "description": "id",
                    "type": "integer"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string"
                },
                "sex": {
                    "description": "性别 1男 2女 3未知",
                    "type": "integer"
                },
                "token": {
                    "description": "token",
                    "type": "string"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "integer"
                },
                "user_name": {
                    "description": "用户名",
                    "type": "string"
                },
                "uuid": {
                    "description": "uuid  自动生成",
                    "type": "integer"
                }
            }
        },
        "response.Code": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "ICQQG接囗文档",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate_swagger,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
