// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate_swagger = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Xfdada",
            "email": "xiangfudada@163.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/get_token": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "获取token",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/news": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "新闻相关接口"
                ],
                "summary": "新增新闻",
                "parameters": [
                    {
                        "type": "string",
                        "description": "新闻标题",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "新闻描述",
                        "name": "desc",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "新闻图",
                        "name": "thumb",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "新闻关键词",
                        "name": "seo_keyword",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "新闻tag",
                        "name": "tags",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "新闻内容",
                        "name": "content",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "新闻类别",
                        "name": "cate_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "新闻点赞数",
                        "name": "zan",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "新闻热门",
                        "name": "hot",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "新闻查看数",
                        "name": "see_num",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "新闻是否置顶",
                        "name": "type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "新闻是否显示",
                        "name": "show",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 200, \"msg\": \"success\"}",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "400": {
                        "description": "{\"code\": 101, \"msg\": \"参数错误\"} 请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "{\"code\": 102, \"msg\": \"未找到结果\"} 内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            }
        },
        "/api/v1/news/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "新闻相关接口"
                ],
                "summary": "通过ID获取新闻详细信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "新闻ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/model.News"
                        }
                    },
                    "400": {
                        "description": "code\": 101, \"msg\": \"参数错误\"} \"请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "code\": 102, \"msg\": \"未找到结果\"} \"内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/upload": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图片上传接口"
                ],
                "summary": "图片上传",
                "parameters": [
                    {
                        "type": "file",
                        "description": "file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 200, \"msg\": \"success\"}",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "400": {
                        "description": "{\"code\": 101, \"msg\": \"参数错误\"} 请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    },
                    "500": {
                        "description": "{\"code\": 102, \"msg\": \"未找到结果\"} 内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Code"
                        }
                    }
                }
            }
        },
        "/api/v1/user": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户接口"
                ],
                "summary": "新增用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": " 用户名",
                        "name": "user_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " 手机号",
                        "name": "mobile",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " 密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " 邮箱",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    },
                    "400": {
                        "description": "请求错误"
                    },
                    "500": {
                        "description": "内部错误"
                    }
                }
            }
        },
        "/api/v1/user/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户接口"
                ],
                "summary": "获取用户详细信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    "400": {
                        "description": "请求错误"
                    },
                    "500": {
                        "description": "内部错误"
                    }
                }
            }
        }
    },
    "definitions": {
        "model.News": {
            "type": "object",
            "properties": {
                "cate_id": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "hot": {
                    "type": "integer"
                },
                "id": {
                    "description": "id",
                    "type": "integer"
                },
                "see_num": {
                    "type": "integer"
                },
                "seo_keyword": {
                    "type": "string"
                },
                "show": {
                    "type": "integer"
                },
                "tags": {
                    "type": "string"
                },
                "thumb": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                },
                "zan": {
                    "type": "integer"
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "id": {
                    "description": "id",
                    "type": "integer"
                },
                "mobile": {
                    "description": "手机号",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "token": {
                    "description": "token",
                    "type": "string"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                },
                "user_name": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "response.Code": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "ICQQG接囗文档",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate_swagger,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
